"""
📝 محرّك البيانات الوصفية — العنوان والوصف والوسوم والهاشتاجات (من أ ل ي)
=========================================================================
ده اللي بيفهم يوتيوب: عنوان بيفتح الشهية · وصف فيه الكلمات اللي الناس بتدوّر بيها ·
وسوم صح · هاشتاجات · فصول (Chapters) للفيديوهات الطويلة · إفصاح AI · وترجمة العنوان
لأكتر اللغات (قناتنا عالمية).

الواجهة:
    md = meta.build({"pillar": "sleep", "kw": "Rain Sounds", "hours": 10})
    meta.validate(md)            # فحص كامل قبل النشر
    meta.write_package(md, "out/")  # JSON + نص جاهز للنسخ
"""
from __future__ import annotations

import json
import pathlib
import re

MAX_TITLE = 100
MAX_TAGS_CHARS = 500
MAX_HASHTAGS = 15

CATEGORY = {"sleep": "10", "focus": "10", "story": "1", "satisfying": "24"}   # Music / Film / Entertainment

PILLAR_KW = {
    "sleep": ["sleep sounds", "rain sounds for sleeping", "heavy rain", "thunderstorm",
              "black screen", "deep sleep", "insomnia relief", "white noise", "8 hours", "10 hours"],
    "focus": ["study sounds", "focus music", "brown noise", "concentration", "homework",
              "deep work", "ambient"],
    "story": ["wordless story", "silent animation", "animation short", "cute", "family friendly",
              "no dialogue", "visual story"],
    "satisfying": ["oddly satisfying", "kinetic sand", "satisfying video", "sand art",
                   "hypnotic", "relaxing video", "asmr"],
}

PILLAR_TAGS = {
    "sleep": ["sleep", "rain sounds", "rain for sleeping", "thunderstorm", "black screen",
              "8 hours", "10 hours", "deep sleep", "insomnia", "white noise", "nature sounds",
              "heavy rain", "relaxing sounds", "sleep music", "rain on window"],
    "focus": ["brown noise", "study", "focus", "concentration", "ambient", "white noise",
              "deep work", "homework", "library sounds", "rain study"],
    "story": ["animation", "short film", "wordless", "silent story", "cute animation", "family",
              "cartoon", "original characters", "no dialogue", "kids safe"],
    "satisfying": ["satisfying", "oddly satisfying", "kinetic sand", "sand art", "asmr",
                   "relaxing", "no talking", "hypnotic", "shorts", "simulation"],
}

# صيغ العنوان لكل لغة (مبنية على أعلى الفيديوهات مشاهدةً في البحث بتاعنا)
TITLE_I18N = {
    "ar": "{kw} للنوم العميق | {dur}",
    "en": "{kw} for Deep Sleep | {dur}",
    "es": "{kw} para dormir profundamente | {dur}",
    "pt": "{kw} para dormir profundamente | {dur}",
    "hi": "{kw} गहरी नींद के लिए | {dur}",
    "id": "{kw} untuk tidur nyenyak | {dur}",
    "de": "{kw} für tiefen Schlaf | {dur}",
    "fr": "{kw} pour un sommeil profond | {dur}",
    "tr": "{kw} derin uyku için | {dur}",
    "ru": "{kw} для глубокого сна | {dur}",
}

DISCLOSURE = ("AI disclosure: this video's visuals and sounds are 100% generated by our own code "
              "(no stock footage, no third-party clips). Names of AI tools are disclosed here per "
              "YouTube's altered-content policy.")

OWNERSHIP = ("All visuals, sounds, music and characters in this video are original works generated "
             "in-house by Dollars Studio. Licensed for YouTube distribution by the creator. "
             "No third-party copyrighted material is used.")


def _chapters(hours: float | None, minutes: float | None) -> list:
    """فصول كل ساعة — عادة أقوى فيديوهات النوم (يتنقّل المشاهد ويثبت أكتر)."""
    out = ["0:00 Start"]
    if hours:
        total = int(round(hours))
        for h in range(1, total + (1 if total <= 3 else 0)):
            out.append(f"{h}:00:00" if h >= 1 else "0:00")
        if total > 3:
            out = ["0:00 Start"] + [f"{h}:00:00 Hour {h}" for h in range(1, total, max(1, total // 10))]
    elif minutes:
        m = int(round(minutes))
        step = 1 if m <= 5 else 2
        for k in range(step, m, step):
            out.append(f"{k}:00")
    return out


def _fmt_dur(hours=None, minutes=None, seconds=None) -> str:
    if hours:
        return f"{hours} Hours"
    if minutes:
        return f"{minutes} Minutes"
    return f"{seconds} seconds"


def _smart(spec: dict) -> dict:
    """بيانات من الكوبي الذكي (عنوان/وصف/وسوم/ترجمات) — لو المساعدين متاحين."""
    try:
        from engine import copy as _copy
        return _copy.enrich(spec)
    except Exception:
        return {}


def build(spec: dict) -> dict:
    """
    spec: pillar · kw (كلمة مفتاحية إنجليزية) · hours/minutes/seconds · scene · character · hook ·
          duration_bucket · kind (long/short) · playlist
    """
    pillar = spec.get("pillar", "sleep")
    kw = spec.get("kw") or {"sleep": "Rain Sounds", "focus": "Brown Noise",
                            "story": "A Wordless Story", "satisfying": "Kinetic Sand"}[pillar]
    hours, minutes, seconds = spec.get("hours"), spec.get("minutes"), spec.get("seconds")
    dur = _fmt_dur(hours, minutes, seconds)
    kind = spec.get("kind") or ("short" if (seconds or (minutes and minutes <= 4)) and not hours else "long")
    name = spec.get("character") or "our little hero"

    base_titles = []
    if pillar == "sleep":
        base_titles = [f"{kw} for Sleeping | {dur} Black Screen | Deep Sleep, Insomnia Relief",
                       f"{kw} • {dur} • No Music, Just {kw} (Black Screen)",
                       f"Fall Asleep in 3 Minutes: {kw} for {dur}"]
    elif pillar == "focus":
        base_titles = [f"{kw} for Studying & Focus | {dur} | Deep Work, No Interruptions",
                       f"Study With Me — {kw} ({dur}) Black Screen",
                       f"{kw} • {dur} • Concentration & Calm"]
    elif pillar == "story":
        thing = spec.get("thing", "the little rain cloud")
        base_titles = [f"{name} and {thing} — a wordless story",
                       f"The {thing} | a tiny wordless tale",
                       f"{name} learns something new (wordless animation, no dialogue)"]
    else:
        base_titles = [f"{kw} — oddly satisfying ({seconds or 30}s)",
                       f"Perfect {kw} | satisfying loop",
                       f"{kw} that no one can stop watching"]

    titles = [t[:MAX_TITLE] for t in base_titles[:3]]
    hashtags = ([f"#{kw.replace(' ', '')}", "#shorts"] if kind == "short" else []) + \
               [f"#{h.replace(' ', '')}" for h in PILLAR_KW[pillar][:8]]
    hashtags = [h for h in dict.fromkeys(hashtags)][:MAX_HASHTAGS]
    # عبارات البحث الحقيقية (من refs.search_demand) — بتزود الوسوم بكلمات الناس بتكتبها فعلًا
    phrases = [str(x).lower() for x in (spec.get("phrases") or []) if x]
    tags = list(dict.fromkeys(
        [kw.lower()] + phrases[:4] + PILLAR_TAGS[pillar] + [t.lower() for t in (spec.get("extra_tags") or [])]))
    # الوسوم ≤ 500 حرف
    picked, ln = [], 0
    for t in tags:
        if ln + len(t) + 1 > MAX_TAGS_CHARS:
            break
        picked.append(t); ln += len(t) + 1

    chapters = _chapters(hours, minutes) if kind == "long" else []
    desc_lines = [
        f"{kw} — {dur} of {kw.lower()} to help you sleep, study or simply relax. "
        f"{'Black screen, no music, no talking.' if pillar in ('sleep', 'focus') else 'No talking — '
         'everything is visual so anyone in the world can enjoy it.'}",
        f"Perfect for: sleep · insomnia · studying · meditation · baby bedtime · stress relief. "
        f"Play it low, dim the screen and let it run all night.",
        "",
        "⏱️ Chapters:" if chapters else "",
        *chapters,
        "" if chapters else "",
        "🎧 What you hear: " + (spec.get("audio_desc") or "rain, thunder and distant storm — generated "
                                "in our studio, no recordings taken from anyone."),
        "🎬 What you see: " + (spec.get("video_desc") or "a living scene rendered frame-by-frame by our "
                                "own engine (moving particles, real motion — not a still picture)."),
        "",
        "💛 " + (spec.get("cta") or "If this helps you sleep, subscribe — we publish a new ambience "
                                   "every day, and shorts every hour."),
        "",
        f"{DISCLOSURE}",
        f"{OWNERSHIP}",
        "",
        " ".join(hashtags),
        "",
        (" · ".join(PILLAR_KW[pillar][:10])) + ".",
        ("🔎 People also search for: " + " · ".join(phrases[:5]) + ".") if phrases else "",
        (f"🎬 Montage: {spec['montage_line']}" if spec.get("montage_line") else ""),
    ]
    description = "\n".join(l for l in desc_lines)
    thumb_texts = {
        "sleep": [f"{dur}", "SLEEP IN 3 MIN", f"{kw.upper()}"],
        "focus": [f"{dur} STUDY", "DEEP FOCUS", kw.upper()],
        "story": [name.upper(), "WORDLESS", "NO DIALOGUE"],
        "satisfying": ["SO SATISFYING", f"{seconds or 30} SEC", kw.upper()],
    }[pillar]

    md = {
        "pillar": pillar, "kind": kind, "kw": kw,
        "titles": titles, "title_i18n": {k: v.format(kw=kw, dur=dur) for k, v in TITLE_I18N.items()},
        "description": description, "tags": picked, "hashtags": hashtags,
        "pinned_comment": spec.get("pinned_comment") or
        ("Which one should we make next: 10 hours of rain, or 10 hours of ocean? 💙 "
         "(We read every comment.)" if kind == "long" else
         "Save this for tonight 😴 Tell us where you are watching from — we love seeing the map fill up!"),
        "thumbnail_texts": thumb_texts,
        "chapters": chapters,
        "playlist": spec.get("playlist") or {"sleep": "Sleep & Rain", "focus": "Focus & Study",
                                             "story": "Wordless Stories", "satisfying": "Satisfying"}[pillar],
        "category_id": CATEGORY[pillar],
        "default_language": spec.get("default_language", "en"),
        "made_for_kids": False,               # family-safe لكن مش «مصنوع للأطفال» (الإعلانات المخصّصة تفضل)
        "license": "standard",
        "disclosure": {"altered_or_synthetic": True, "note": DISCLOSURE},
        "end_screen": {"after_seconds": 20, "elements": ["subscribe", "best_for_viewer", "playlist"]},
        "cards": [{"at": "01:00", "type": "playlist", "playlist": "Sleep & Rain"}],
        "upload_defaults": {"comments": "allow", "ratings": "allow", "embedding": True,
                            "visibility": spec.get("visibility", "public")},
    }
    if kind == "short":
        md["titles"] = [t if t.endswith("#shorts") else (t[:80] + " #shorts") for t in md["titles"]]
        md["chapters"] = []
        md["description"] = description.replace("⏱️ Chapters:", "").strip()
    # ── الكوبي الذكي: عنوان مغناطيسي + كلمات طلب حقيقي + لغات الدنيا ──
    try:
        smart = _smart(spec) if spec.get("smart", True) else {}
    except Exception:
        smart = {}
    if smart:
        for t in smart.get("titles", []):
            if kind == "short" and not t.rstrip().endswith("#shorts"):
                t = t.strip()[:80] + " #shorts"
            if 12 <= len(t) <= MAX_TITLE and not t.isupper():
                md["titles"] = [t] + [x for x in md["titles"] if x != t]
        md["titles"] = md["titles"][:3]
        real_tags = [t for t in smart.get("tags", []) if t and t.lower() != kw.lower()]
        if real_tags:                                    # كلمات الطلب الحقيقي في المقدمة
            merged = real_tags + [t for t in md["tags"] if t not in real_tags]
            total, picked = 0, []
            for t in merged:
                if total + len(t) + 1 > MAX_TAGS_CHARS - 20:
                    break
                picked.append(t); total += len(t) + 1
            md["tags"] = picked[:35]
        if smart.get("description") and len(smart["description"]) > 120:
            keep = [ln for ln in md["description"].splitlines()
                    if any(k in ln.lower() for k in ("disclos", "إفصاح", "generated", "مولّد",
                                                     "license", "حقوق", "studio", "subscribe"))]
            md["description"] = (smart["description"] + ("\n\n" + "\n".join(keep[:6]) if keep else "")
                                 )[:4900]
        if smart.get("hook"):
            md["hook"] = smart["hook"]
        if smart.get("localizations"):
            md["localizations"] = smart["localizations"]
        if smart.get("suggests"):
            md["search_demand"] = smart["suggests"][:12]
    return md


def validate(md: dict) -> list:
    """فحص كامل قبل النشر — بيرجّع قائمة المشاكل (فاضية = تمام)."""
    problems = []
    for i, t in enumerate(md.get("titles", [])):
        if len(t) > MAX_TITLE:
            problems.append(f"العنوان {i+1} أطول من {MAX_TITLE} حرف ({len(t)})")
        if len(t) < 12:
            problems.append(f"العنوان {i+1} قصير جدًا")
        if t.isupper() and len(t) > 30:
            problems.append(f"العنوان {i+1} كله كابيتال (سبام)")
    desc = md.get("description", "")
    if len(desc) < 300:
        problems.append("الوصف قصير جدًا (أقل من 300 حرف) — ضعيف للبحث")
    if md.get("kw", "").lower() not in desc.lower():
        problems.append("الكلمة المفتاحية مش موجودة في الوصف")
    low = desc.lower()
    if "ai disclosure" not in low and not ("disclos" in low and "generated" in low):
        problems.append("مفيش إفصاح واضح عن المحتوى المولّد بالذكاء الاصطناعي")
    tags = md.get("tags", [])
    if sum(len(t) + 1 for t in tags) > MAX_TAGS_CHARS:
        problems.append("الوسوم أطول من 500 حرف")
    if not tags:
        problems.append("مفيش وسوم")
    if len(md.get("hashtags", [])) > MAX_HASHTAGS:
        problems.append(f"أكثر من {MAX_HASHTAGS} هاشتاج (يوتيوب بيرفضها)")
    if md.get("kind") == "long" and len(desc) > 120 and "⏱️" not in desc:
        problems.append("فيديو طويل من غير فصول (Chapters)")
    if md.get("made_for_kids"):
        problems.append("⚠️ «مصنوع للأطفال» = إعلانات أقل 50-80% — تأكد إن ده مقصود")
    bad = re.findall(r"(free money|guaranteed income|click here|get rich)", desc, re.I)
    if bad:
        problems.append(f"عبارات ممنوعة في الوصف: {bad}")
    return problems


def write_package(md: dict, out_dir="out") -> dict:
    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    slug = re.sub(r"[^a-z0-9]+", "-", md["kw"].lower()).strip("-")[:40] or "video"
    j = out / f"{slug}.meta.json"
    j.write_text(json.dumps(md, ensure_ascii=False, indent=2), encoding="utf-8")
    txt = out / f"{slug}.meta.txt"
    txt.write_text(
        f"العنوان (A): {md['titles'][0]}\nالعنوان (B): {md['titles'][1]}\n"
        f"العنوان (C): {md['titles'][2]}\n\n=== الوصف ===\n{md['description']}\n\n"
        f"=== الوسوم ===\n{', '.join(md['tags'])}\n\n=== أول تعليق مثبّت ===\n{md['pinned_comment']}\n\n"
        f"=== نص الغلاف (3 بدائل) ===\n" + "\n".join(f"- {t}" for t in md["thumbnail_texts"]) + "\n\n"
        f"=== عناوين بلغات العالم ===\n" + "\n".join(f"{k}: {v}" for k, v in md["title_i18n"].items()),
        encoding="utf-8")
    return {"json": str(j), "text": str(txt)}


if __name__ == "__main__":
    demo = build({"pillar": "sleep", "kw": "Heavy Rain on Window", "hours": 10,
                  "scene": "rain_glass", "audio_desc": "rain on glass + distant thunder"})
    print(demo["titles"][0])
    print("مشاكل:", validate(demo) or "مفيش ✅")
    print(write_package(demo, "out"))
